version: 2.1

jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a1:47:21:99:5f:63:03:93:30:7c:72:a1:90:c9:b1:19"
      - run: ls ~/.ssh/
      - run: cd $HOME && git clone --mirror $CIRCLE_REPOSITORY_URL ${CIRCLE_PROJECT_REPONAME}_mirror
      - run: cd $HOME/${CIRCLE_PROJECT_REPONAME}_mirror && git remote add mirror-remote ssh://git@git.ioweb.fr:322/misc/github-mirror.git
      - run: cd $HOME/${CIRCLE_PROJECT_REPONAME}_mirror && git push --mirror --tags -f mirror-remote && git remote prune mirror-remote
